/*
CONS3RT API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@cons3rt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gocons3rt

import (
	"encoding/json"
)

// ActiveCompositionStatus struct for ActiveCompositionStatus
type ActiveCompositionStatus struct {
	DeploymentRunId *int32 `json:"deploymentRunId,omitempty"`
	DeploymentRunStatus *string `json:"deploymentRunStatus,omitempty"`
	DeploymentRunHost *[]MinimalDeploymentRunHost `json:"deploymentRunHost,omitempty"`
}

// NewActiveCompositionStatus instantiates a new ActiveCompositionStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActiveCompositionStatus(type_ string) *ActiveCompositionStatus {
	this := ActiveCompositionStatus{}
	this.Type = type_
	return &this
}

// NewActiveCompositionStatusWithDefaults instantiates a new ActiveCompositionStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActiveCompositionStatusWithDefaults() *ActiveCompositionStatus {
	this := ActiveCompositionStatus{}
	return &this
}

// GetDeploymentRunId returns the DeploymentRunId field value if set, zero value otherwise.
func (o *ActiveCompositionStatus) GetDeploymentRunId() int32 {
	if o == nil || o.DeploymentRunId == nil {
		var ret int32
		return ret
	}
	return *o.DeploymentRunId
}

// GetDeploymentRunIdOk returns a tuple with the DeploymentRunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveCompositionStatus) GetDeploymentRunIdOk() (*int32, bool) {
	if o == nil || o.DeploymentRunId == nil {
		return nil, false
	}
	return o.DeploymentRunId, true
}

// HasDeploymentRunId returns a boolean if a field has been set.
func (o *ActiveCompositionStatus) HasDeploymentRunId() bool {
	if o != nil && o.DeploymentRunId != nil {
		return true
	}

	return false
}

// SetDeploymentRunId gets a reference to the given int32 and assigns it to the DeploymentRunId field.
func (o *ActiveCompositionStatus) SetDeploymentRunId(v int32) {
	o.DeploymentRunId = &v
}

// GetDeploymentRunStatus returns the DeploymentRunStatus field value if set, zero value otherwise.
func (o *ActiveCompositionStatus) GetDeploymentRunStatus() string {
	if o == nil || o.DeploymentRunStatus == nil {
		var ret string
		return ret
	}
	return *o.DeploymentRunStatus
}

// GetDeploymentRunStatusOk returns a tuple with the DeploymentRunStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveCompositionStatus) GetDeploymentRunStatusOk() (*string, bool) {
	if o == nil || o.DeploymentRunStatus == nil {
		return nil, false
	}
	return o.DeploymentRunStatus, true
}

// HasDeploymentRunStatus returns a boolean if a field has been set.
func (o *ActiveCompositionStatus) HasDeploymentRunStatus() bool {
	if o != nil && o.DeploymentRunStatus != nil {
		return true
	}

	return false
}

// SetDeploymentRunStatus gets a reference to the given string and assigns it to the DeploymentRunStatus field.
func (o *ActiveCompositionStatus) SetDeploymentRunStatus(v string) {
	o.DeploymentRunStatus = &v
}

// GetDeploymentRunHost returns the DeploymentRunHost field value if set, zero value otherwise.
func (o *ActiveCompositionStatus) GetDeploymentRunHost() []MinimalDeploymentRunHost {
	if o == nil || o.DeploymentRunHost == nil {
		var ret []MinimalDeploymentRunHost
		return ret
	}
	return *o.DeploymentRunHost
}

// GetDeploymentRunHostOk returns a tuple with the DeploymentRunHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveCompositionStatus) GetDeploymentRunHostOk() (*[]MinimalDeploymentRunHost, bool) {
	if o == nil || o.DeploymentRunHost == nil {
		return nil, false
	}
	return o.DeploymentRunHost, true
}

// HasDeploymentRunHost returns a boolean if a field has been set.
func (o *ActiveCompositionStatus) HasDeploymentRunHost() bool {
	if o != nil && o.DeploymentRunHost != nil {
		return true
	}

	return false
}

// SetDeploymentRunHost gets a reference to the given []MinimalDeploymentRunHost and assigns it to the DeploymentRunHost field.
func (o *ActiveCompositionStatus) SetDeploymentRunHost(v []MinimalDeploymentRunHost) {
	o.DeploymentRunHost = &v
}

func (o ActiveCompositionStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DeploymentRunId != nil {
		toSerialize["deploymentRunId"] = o.DeploymentRunId
	}
	if o.DeploymentRunStatus != nil {
		toSerialize["deploymentRunStatus"] = o.DeploymentRunStatus
	}
	if o.DeploymentRunHost != nil {
		toSerialize["deploymentRunHost"] = o.DeploymentRunHost
	}
	return json.Marshal(toSerialize)
}

type NullableActiveCompositionStatus struct {
	value *ActiveCompositionStatus
	isSet bool
}

func (v NullableActiveCompositionStatus) Get() *ActiveCompositionStatus {
	return v.value
}

func (v *NullableActiveCompositionStatus) Set(val *ActiveCompositionStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableActiveCompositionStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableActiveCompositionStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActiveCompositionStatus(val *ActiveCompositionStatus) *NullableActiveCompositionStatus {
	return &NullableActiveCompositionStatus{value: val, isSet: true}
}

func (v NullableActiveCompositionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActiveCompositionStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


