/*
CONS3RT API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@cons3rt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cons3rt

import (
	"encoding/json"
)

// MinimalSoftwareComponent struct for MinimalSoftwareComponent
type MinimalSoftwareComponent struct {
	Asset          MinimalAsset `json:"asset"`
	Id             *int32       `json:"id,omitempty"`
	LoadOrder      *int32       `json:"loadOrder,omitempty"`
	RebootDelay    *int32       `json:"rebootDelay,omitempty"`
	RebootRequired *bool        `json:"rebootRequired,omitempty"`
}

// NewMinimalSoftwareComponent instantiates a new MinimalSoftwareComponent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMinimalSoftwareComponent(asset MinimalAsset) *MinimalSoftwareComponent {
	this := MinimalSoftwareComponent{}
	this.Asset = asset
	return &this
}

// NewMinimalSoftwareComponentWithDefaults instantiates a new MinimalSoftwareComponent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMinimalSoftwareComponentWithDefaults() *MinimalSoftwareComponent {
	this := MinimalSoftwareComponent{}
	return &this
}

// GetAsset returns the Asset field value
func (o *MinimalSoftwareComponent) GetAsset() MinimalAsset {
	if o == nil {
		var ret MinimalAsset
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *MinimalSoftwareComponent) GetAssetOk() (*MinimalAsset, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *MinimalSoftwareComponent) SetAsset(v MinimalAsset) {
	o.Asset = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MinimalSoftwareComponent) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimalSoftwareComponent) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MinimalSoftwareComponent) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *MinimalSoftwareComponent) SetId(v int32) {
	o.Id = &v
}

// GetLoadOrder returns the LoadOrder field value if set, zero value otherwise.
func (o *MinimalSoftwareComponent) GetLoadOrder() int32 {
	if o == nil || o.LoadOrder == nil {
		var ret int32
		return ret
	}
	return *o.LoadOrder
}

// GetLoadOrderOk returns a tuple with the LoadOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimalSoftwareComponent) GetLoadOrderOk() (*int32, bool) {
	if o == nil || o.LoadOrder == nil {
		return nil, false
	}
	return o.LoadOrder, true
}

// HasLoadOrder returns a boolean if a field has been set.
func (o *MinimalSoftwareComponent) HasLoadOrder() bool {
	if o != nil && o.LoadOrder != nil {
		return true
	}

	return false
}

// SetLoadOrder gets a reference to the given int32 and assigns it to the LoadOrder field.
func (o *MinimalSoftwareComponent) SetLoadOrder(v int32) {
	o.LoadOrder = &v
}

// GetRebootDelay returns the RebootDelay field value if set, zero value otherwise.
func (o *MinimalSoftwareComponent) GetRebootDelay() int32 {
	if o == nil || o.RebootDelay == nil {
		var ret int32
		return ret
	}
	return *o.RebootDelay
}

// GetRebootDelayOk returns a tuple with the RebootDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimalSoftwareComponent) GetRebootDelayOk() (*int32, bool) {
	if o == nil || o.RebootDelay == nil {
		return nil, false
	}
	return o.RebootDelay, true
}

// HasRebootDelay returns a boolean if a field has been set.
func (o *MinimalSoftwareComponent) HasRebootDelay() bool {
	if o != nil && o.RebootDelay != nil {
		return true
	}

	return false
}

// SetRebootDelay gets a reference to the given int32 and assigns it to the RebootDelay field.
func (o *MinimalSoftwareComponent) SetRebootDelay(v int32) {
	o.RebootDelay = &v
}

// GetRebootRequired returns the RebootRequired field value if set, zero value otherwise.
func (o *MinimalSoftwareComponent) GetRebootRequired() bool {
	if o == nil || o.RebootRequired == nil {
		var ret bool
		return ret
	}
	return *o.RebootRequired
}

// GetRebootRequiredOk returns a tuple with the RebootRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimalSoftwareComponent) GetRebootRequiredOk() (*bool, bool) {
	if o == nil || o.RebootRequired == nil {
		return nil, false
	}
	return o.RebootRequired, true
}

// HasRebootRequired returns a boolean if a field has been set.
func (o *MinimalSoftwareComponent) HasRebootRequired() bool {
	if o != nil && o.RebootRequired != nil {
		return true
	}

	return false
}

// SetRebootRequired gets a reference to the given bool and assigns it to the RebootRequired field.
func (o *MinimalSoftwareComponent) SetRebootRequired(v bool) {
	o.RebootRequired = &v
}

func (o MinimalSoftwareComponent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["asset"] = o.Asset
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.LoadOrder != nil {
		toSerialize["loadOrder"] = o.LoadOrder
	}
	if o.RebootDelay != nil {
		toSerialize["rebootDelay"] = o.RebootDelay
	}
	if o.RebootRequired != nil {
		toSerialize["rebootRequired"] = o.RebootRequired
	}
	return json.Marshal(toSerialize)
}

type NullableMinimalSoftwareComponent struct {
	value *MinimalSoftwareComponent
	isSet bool
}

func (v NullableMinimalSoftwareComponent) Get() *MinimalSoftwareComponent {
	return v.value
}

func (v *NullableMinimalSoftwareComponent) Set(val *MinimalSoftwareComponent) {
	v.value = val
	v.isSet = true
}

func (v NullableMinimalSoftwareComponent) IsSet() bool {
	return v.isSet
}

func (v *NullableMinimalSoftwareComponent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMinimalSoftwareComponent(val *MinimalSoftwareComponent) *NullableMinimalSoftwareComponent {
	return &NullableMinimalSoftwareComponent{value: val, isSet: true}
}

func (v NullableMinimalSoftwareComponent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMinimalSoftwareComponent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
