/*
CONS3RT API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@cons3rt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gocons3rt

import (
	"encoding/json"
)

// AddAzureNetworkRequest struct for AddAzureNetworkRequest
type AddAzureNetworkRequest struct {
	NatInstanceType   string            `json:"natInstanceType"`
	NatImageReference ImageReferenceDTO `json:"natImageReference"`
	Network           Network
	Subtype           string
}

// NewAddAzureNetworkRequest instantiates a new AddAzureNetworkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAzureNetworkRequest(natInstanceType string, natImageReference ImageReferenceDTO, network Network, subtype string) *AddAzureNetworkRequest {
	this := AddAzureNetworkRequest{}
	this.Network = network
	this.Subtype = subtype
	this.NatInstanceType = natInstanceType
	this.NatImageReference = natImageReference
	return &this
}

// NewAddAzureNetworkRequestWithDefaults instantiates a new AddAzureNetworkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAzureNetworkRequestWithDefaults() *AddAzureNetworkRequest {
	this := AddAzureNetworkRequest{}
	return &this
}

// GetNatInstanceType returns the NatInstanceType field value
func (o *AddAzureNetworkRequest) GetNatInstanceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NatInstanceType
}

// GetNatInstanceTypeOk returns a tuple with the NatInstanceType field value
// and a boolean to check if the value has been set.
func (o *AddAzureNetworkRequest) GetNatInstanceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NatInstanceType, true
}

// SetNatInstanceType sets field value
func (o *AddAzureNetworkRequest) SetNatInstanceType(v string) {
	o.NatInstanceType = v
}

// GetNatImageReference returns the NatImageReference field value
func (o *AddAzureNetworkRequest) GetNatImageReference() ImageReferenceDTO {
	if o == nil {
		var ret ImageReferenceDTO
		return ret
	}

	return o.NatImageReference
}

// GetNatImageReferenceOk returns a tuple with the NatImageReference field value
// and a boolean to check if the value has been set.
func (o *AddAzureNetworkRequest) GetNatImageReferenceOk() (*ImageReferenceDTO, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NatImageReference, true
}

// SetNatImageReference sets field value
func (o *AddAzureNetworkRequest) SetNatImageReference(v ImageReferenceDTO) {
	o.NatImageReference = v
}

func (o AddAzureNetworkRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["natInstanceType"] = o.NatInstanceType
	}
	if true {
		toSerialize["natImageReference"] = o.NatImageReference
	}
	return json.Marshal(toSerialize)
}

type NullableAddAzureNetworkRequest struct {
	value *AddAzureNetworkRequest
	isSet bool
}

func (v NullableAddAzureNetworkRequest) Get() *AddAzureNetworkRequest {
	return v.value
}

func (v *NullableAddAzureNetworkRequest) Set(val *AddAzureNetworkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAzureNetworkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAzureNetworkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAzureNetworkRequest(val *AddAzureNetworkRequest) *NullableAddAzureNetworkRequest {
	return &NullableAddAzureNetworkRequest{value: val, isSet: true}
}

func (v NullableAddAzureNetworkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAzureNetworkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
