/*
CONS3RT API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@cons3rt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gocons3rt

import (
	"encoding/json"
)

// ContainerComponent struct for ContainerComponent
type ContainerComponent struct {
	Configuration ContainerConfiguration `json:"configuration"`
}

// NewContainerComponent instantiates a new ContainerComponent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerComponent(configuration ContainerConfiguration, asset Asset, subtype string) *ContainerComponent {
	this := ContainerComponent{}
	this.Asset = asset
	this.Subtype = subtype
	this.Configuration = configuration
	return &this
}

// NewContainerComponentWithDefaults instantiates a new ContainerComponent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerComponentWithDefaults() *ContainerComponent {
	this := ContainerComponent{}
	return &this
}

// GetConfiguration returns the Configuration field value
func (o *ContainerComponent) GetConfiguration() ContainerConfiguration {
	if o == nil {
		var ret ContainerConfiguration
		return ret
	}

	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value
// and a boolean to check if the value has been set.
func (o *ContainerComponent) GetConfigurationOk() (*ContainerConfiguration, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Configuration, true
}

// SetConfiguration sets field value
func (o *ContainerComponent) SetConfiguration(v ContainerConfiguration) {
	o.Configuration = v
}

func (o ContainerComponent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["configuration"] = o.Configuration
	}
	return json.Marshal(toSerialize)
}

type NullableContainerComponent struct {
	value *ContainerComponent
	isSet bool
}

func (v NullableContainerComponent) Get() *ContainerComponent {
	return v.value
}

func (v *NullableContainerComponent) Set(val *ContainerComponent) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerComponent) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerComponent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerComponent(val *ContainerComponent) *NullableContainerComponent {
	return &NullableContainerComponent{value: val, isSet: true}
}

func (v NullableContainerComponent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerComponent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


