/*
CONS3RT API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@cons3rt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gocons3rt

import (
	"encoding/json"
)

// VirtualHost struct for VirtualHost
type VirtualHost struct {
	Subtype string
}

// NewVirtualHost instantiates a new VirtualHost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVirtualHost(subtype string) *VirtualHost {
	this := VirtualHost{}
	this.Subtype = subtype
	return &this
}

// NewVirtualHostWithDefaults instantiates a new VirtualHost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVirtualHostWithDefaults() *VirtualHost {
	this := VirtualHost{}
	return &this
}

func (o VirtualHost) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	return json.Marshal(toSerialize)
}

type NullableVirtualHost struct {
	value *VirtualHost
	isSet bool
}

func (v NullableVirtualHost) Get() *VirtualHost {
	return v.value
}

func (v *NullableVirtualHost) Set(val *VirtualHost) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualHost) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualHost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualHost(val *VirtualHost) *NullableVirtualHost {
	return &NullableVirtualHost{value: val, isSet: true}
}

func (v NullableVirtualHost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualHost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
