/*
CONS3RT API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@cons3rt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cons3rt

import (
	"encoding/json"
)

// FullTestAsset struct for FullTestAsset
type FullTestAsset struct {
	Type    *string `json:"type,omitempty"`
	Subtype string
}

// NewFullTestAsset instantiates a new FullTestAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFullTestAsset(subtype string) *FullTestAsset {
	this := FullTestAsset{}
	this.Subtype = subtype
	return &this
}

// NewFullTestAssetWithDefaults instantiates a new FullTestAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFullTestAssetWithDefaults() *FullTestAsset {
	this := FullTestAsset{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *FullTestAsset) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FullTestAsset) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *FullTestAsset) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *FullTestAsset) SetType(v string) {
	o.Type = &v
}

func (o FullTestAsset) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableFullTestAsset struct {
	value *FullTestAsset
	isSet bool
}

func (v NullableFullTestAsset) Get() *FullTestAsset {
	return v.value
}

func (v *NullableFullTestAsset) Set(val *FullTestAsset) {
	v.value = val
	v.isSet = true
}

func (v NullableFullTestAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableFullTestAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFullTestAsset(val *FullTestAsset) *NullableFullTestAsset {
	return &NullableFullTestAsset{value: val, isSet: true}
}

func (v NullableFullTestAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFullTestAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
