/*
CONS3RT API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@cons3rt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gocons3rt

import (
	"encoding/json"
)

// BasicSoftwareAsset struct for BasicSoftwareAsset
type BasicSoftwareAsset struct {
	SoftwareType *string `json:"softwareType,omitempty"`
}

// NewBasicSoftwareAsset instantiates a new BasicSoftwareAsset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBasicSoftwareAsset(subtype string) *BasicSoftwareAsset {
	this := BasicSoftwareAsset{}
	this.Subtype = subtype
	return &this
}

// NewBasicSoftwareAssetWithDefaults instantiates a new BasicSoftwareAsset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBasicSoftwareAssetWithDefaults() *BasicSoftwareAsset {
	this := BasicSoftwareAsset{}
	return &this
}

// GetSoftwareType returns the SoftwareType field value if set, zero value otherwise.
func (o *BasicSoftwareAsset) GetSoftwareType() string {
	if o == nil || o.SoftwareType == nil {
		var ret string
		return ret
	}
	return *o.SoftwareType
}

// GetSoftwareTypeOk returns a tuple with the SoftwareType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicSoftwareAsset) GetSoftwareTypeOk() (*string, bool) {
	if o == nil || o.SoftwareType == nil {
		return nil, false
	}
	return o.SoftwareType, true
}

// HasSoftwareType returns a boolean if a field has been set.
func (o *BasicSoftwareAsset) HasSoftwareType() bool {
	if o != nil && o.SoftwareType != nil {
		return true
	}

	return false
}

// SetSoftwareType gets a reference to the given string and assigns it to the SoftwareType field.
func (o *BasicSoftwareAsset) SetSoftwareType(v string) {
	o.SoftwareType = &v
}

func (o BasicSoftwareAsset) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SoftwareType != nil {
		toSerialize["softwareType"] = o.SoftwareType
	}
	return json.Marshal(toSerialize)
}

type NullableBasicSoftwareAsset struct {
	value *BasicSoftwareAsset
	isSet bool
}

func (v NullableBasicSoftwareAsset) Get() *BasicSoftwareAsset {
	return v.value
}

func (v *NullableBasicSoftwareAsset) Set(val *BasicSoftwareAsset) {
	v.value = val
	v.isSet = true
}

func (v NullableBasicSoftwareAsset) IsSet() bool {
	return v.isSet
}

func (v *NullableBasicSoftwareAsset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasicSoftwareAsset(val *BasicSoftwareAsset) *NullableBasicSoftwareAsset {
	return &NullableBasicSoftwareAsset{value: val, isSet: true}
}

func (v NullableBasicSoftwareAsset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasicSoftwareAsset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


