/*
CONS3RT API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@cons3rt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cons3rt

import (
	"encoding/json"
)

// DeploymentAssetMetric struct for DeploymentAssetMetric
type DeploymentAssetMetric struct {
	DeploymentId                  *string `json:"deploymentId,omitempty"`
	TotalDeploymentRunDuration    *int64  `json:"totalDeploymentRunDuration,omitempty"`
	AverageDeploymentRunDuration  *int64  `json:"averageDeploymentRunDuration,omitempty"`
	MedianDeploymentRunDuration   *int64  `json:"medianDeploymentRunDuration,omitempty"`
	LongestDeploymentRunDuration  *int64  `json:"longestDeploymentRunDuration,omitempty"`
	ShortestDeploymentRunDuration *int64  `json:"shortestDeploymentRunDuration,omitempty"`
	TotalDeploymentRuns           *int32  `json:"totalDeploymentRuns,omitempty"`
	TotalDeploymentRunSuccess     *int32  `json:"totalDeploymentRunSuccess,omitempty"`
	TotalDeploymentRunError       *int32  `json:"totalDeploymentRunError,omitempty"`
	TotalDeploymentRunCancel      *int32  `json:"totalDeploymentRunCancel,omitempty"`
	TotalDeploymentRunUnknown     *int32  `json:"totalDeploymentRunUnknown,omitempty"`
	TotalVirtualMachines          *int32  `json:"totalVirtualMachines,omitempty"`
}

// NewDeploymentAssetMetric instantiates a new DeploymentAssetMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentAssetMetric() *DeploymentAssetMetric {
	this := DeploymentAssetMetric{}
	return &this
}

// NewDeploymentAssetMetricWithDefaults instantiates a new DeploymentAssetMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentAssetMetricWithDefaults() *DeploymentAssetMetric {
	this := DeploymentAssetMetric{}
	return &this
}

// GetDeploymentId returns the DeploymentId field value if set, zero value otherwise.
func (o *DeploymentAssetMetric) GetDeploymentId() string {
	if o == nil || o.DeploymentId == nil {
		var ret string
		return ret
	}
	return *o.DeploymentId
}

// GetDeploymentIdOk returns a tuple with the DeploymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAssetMetric) GetDeploymentIdOk() (*string, bool) {
	if o == nil || o.DeploymentId == nil {
		return nil, false
	}
	return o.DeploymentId, true
}

// HasDeploymentId returns a boolean if a field has been set.
func (o *DeploymentAssetMetric) HasDeploymentId() bool {
	if o != nil && o.DeploymentId != nil {
		return true
	}

	return false
}

// SetDeploymentId gets a reference to the given string and assigns it to the DeploymentId field.
func (o *DeploymentAssetMetric) SetDeploymentId(v string) {
	o.DeploymentId = &v
}

// GetTotalDeploymentRunDuration returns the TotalDeploymentRunDuration field value if set, zero value otherwise.
func (o *DeploymentAssetMetric) GetTotalDeploymentRunDuration() int64 {
	if o == nil || o.TotalDeploymentRunDuration == nil {
		var ret int64
		return ret
	}
	return *o.TotalDeploymentRunDuration
}

// GetTotalDeploymentRunDurationOk returns a tuple with the TotalDeploymentRunDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAssetMetric) GetTotalDeploymentRunDurationOk() (*int64, bool) {
	if o == nil || o.TotalDeploymentRunDuration == nil {
		return nil, false
	}
	return o.TotalDeploymentRunDuration, true
}

// HasTotalDeploymentRunDuration returns a boolean if a field has been set.
func (o *DeploymentAssetMetric) HasTotalDeploymentRunDuration() bool {
	if o != nil && o.TotalDeploymentRunDuration != nil {
		return true
	}

	return false
}

// SetTotalDeploymentRunDuration gets a reference to the given int64 and assigns it to the TotalDeploymentRunDuration field.
func (o *DeploymentAssetMetric) SetTotalDeploymentRunDuration(v int64) {
	o.TotalDeploymentRunDuration = &v
}

// GetAverageDeploymentRunDuration returns the AverageDeploymentRunDuration field value if set, zero value otherwise.
func (o *DeploymentAssetMetric) GetAverageDeploymentRunDuration() int64 {
	if o == nil || o.AverageDeploymentRunDuration == nil {
		var ret int64
		return ret
	}
	return *o.AverageDeploymentRunDuration
}

// GetAverageDeploymentRunDurationOk returns a tuple with the AverageDeploymentRunDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAssetMetric) GetAverageDeploymentRunDurationOk() (*int64, bool) {
	if o == nil || o.AverageDeploymentRunDuration == nil {
		return nil, false
	}
	return o.AverageDeploymentRunDuration, true
}

// HasAverageDeploymentRunDuration returns a boolean if a field has been set.
func (o *DeploymentAssetMetric) HasAverageDeploymentRunDuration() bool {
	if o != nil && o.AverageDeploymentRunDuration != nil {
		return true
	}

	return false
}

// SetAverageDeploymentRunDuration gets a reference to the given int64 and assigns it to the AverageDeploymentRunDuration field.
func (o *DeploymentAssetMetric) SetAverageDeploymentRunDuration(v int64) {
	o.AverageDeploymentRunDuration = &v
}

// GetMedianDeploymentRunDuration returns the MedianDeploymentRunDuration field value if set, zero value otherwise.
func (o *DeploymentAssetMetric) GetMedianDeploymentRunDuration() int64 {
	if o == nil || o.MedianDeploymentRunDuration == nil {
		var ret int64
		return ret
	}
	return *o.MedianDeploymentRunDuration
}

// GetMedianDeploymentRunDurationOk returns a tuple with the MedianDeploymentRunDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAssetMetric) GetMedianDeploymentRunDurationOk() (*int64, bool) {
	if o == nil || o.MedianDeploymentRunDuration == nil {
		return nil, false
	}
	return o.MedianDeploymentRunDuration, true
}

// HasMedianDeploymentRunDuration returns a boolean if a field has been set.
func (o *DeploymentAssetMetric) HasMedianDeploymentRunDuration() bool {
	if o != nil && o.MedianDeploymentRunDuration != nil {
		return true
	}

	return false
}

// SetMedianDeploymentRunDuration gets a reference to the given int64 and assigns it to the MedianDeploymentRunDuration field.
func (o *DeploymentAssetMetric) SetMedianDeploymentRunDuration(v int64) {
	o.MedianDeploymentRunDuration = &v
}

// GetLongestDeploymentRunDuration returns the LongestDeploymentRunDuration field value if set, zero value otherwise.
func (o *DeploymentAssetMetric) GetLongestDeploymentRunDuration() int64 {
	if o == nil || o.LongestDeploymentRunDuration == nil {
		var ret int64
		return ret
	}
	return *o.LongestDeploymentRunDuration
}

// GetLongestDeploymentRunDurationOk returns a tuple with the LongestDeploymentRunDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAssetMetric) GetLongestDeploymentRunDurationOk() (*int64, bool) {
	if o == nil || o.LongestDeploymentRunDuration == nil {
		return nil, false
	}
	return o.LongestDeploymentRunDuration, true
}

// HasLongestDeploymentRunDuration returns a boolean if a field has been set.
func (o *DeploymentAssetMetric) HasLongestDeploymentRunDuration() bool {
	if o != nil && o.LongestDeploymentRunDuration != nil {
		return true
	}

	return false
}

// SetLongestDeploymentRunDuration gets a reference to the given int64 and assigns it to the LongestDeploymentRunDuration field.
func (o *DeploymentAssetMetric) SetLongestDeploymentRunDuration(v int64) {
	o.LongestDeploymentRunDuration = &v
}

// GetShortestDeploymentRunDuration returns the ShortestDeploymentRunDuration field value if set, zero value otherwise.
func (o *DeploymentAssetMetric) GetShortestDeploymentRunDuration() int64 {
	if o == nil || o.ShortestDeploymentRunDuration == nil {
		var ret int64
		return ret
	}
	return *o.ShortestDeploymentRunDuration
}

// GetShortestDeploymentRunDurationOk returns a tuple with the ShortestDeploymentRunDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAssetMetric) GetShortestDeploymentRunDurationOk() (*int64, bool) {
	if o == nil || o.ShortestDeploymentRunDuration == nil {
		return nil, false
	}
	return o.ShortestDeploymentRunDuration, true
}

// HasShortestDeploymentRunDuration returns a boolean if a field has been set.
func (o *DeploymentAssetMetric) HasShortestDeploymentRunDuration() bool {
	if o != nil && o.ShortestDeploymentRunDuration != nil {
		return true
	}

	return false
}

// SetShortestDeploymentRunDuration gets a reference to the given int64 and assigns it to the ShortestDeploymentRunDuration field.
func (o *DeploymentAssetMetric) SetShortestDeploymentRunDuration(v int64) {
	o.ShortestDeploymentRunDuration = &v
}

// GetTotalDeploymentRuns returns the TotalDeploymentRuns field value if set, zero value otherwise.
func (o *DeploymentAssetMetric) GetTotalDeploymentRuns() int32 {
	if o == nil || o.TotalDeploymentRuns == nil {
		var ret int32
		return ret
	}
	return *o.TotalDeploymentRuns
}

// GetTotalDeploymentRunsOk returns a tuple with the TotalDeploymentRuns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAssetMetric) GetTotalDeploymentRunsOk() (*int32, bool) {
	if o == nil || o.TotalDeploymentRuns == nil {
		return nil, false
	}
	return o.TotalDeploymentRuns, true
}

// HasTotalDeploymentRuns returns a boolean if a field has been set.
func (o *DeploymentAssetMetric) HasTotalDeploymentRuns() bool {
	if o != nil && o.TotalDeploymentRuns != nil {
		return true
	}

	return false
}

// SetTotalDeploymentRuns gets a reference to the given int32 and assigns it to the TotalDeploymentRuns field.
func (o *DeploymentAssetMetric) SetTotalDeploymentRuns(v int32) {
	o.TotalDeploymentRuns = &v
}

// GetTotalDeploymentRunSuccess returns the TotalDeploymentRunSuccess field value if set, zero value otherwise.
func (o *DeploymentAssetMetric) GetTotalDeploymentRunSuccess() int32 {
	if o == nil || o.TotalDeploymentRunSuccess == nil {
		var ret int32
		return ret
	}
	return *o.TotalDeploymentRunSuccess
}

// GetTotalDeploymentRunSuccessOk returns a tuple with the TotalDeploymentRunSuccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAssetMetric) GetTotalDeploymentRunSuccessOk() (*int32, bool) {
	if o == nil || o.TotalDeploymentRunSuccess == nil {
		return nil, false
	}
	return o.TotalDeploymentRunSuccess, true
}

// HasTotalDeploymentRunSuccess returns a boolean if a field has been set.
func (o *DeploymentAssetMetric) HasTotalDeploymentRunSuccess() bool {
	if o != nil && o.TotalDeploymentRunSuccess != nil {
		return true
	}

	return false
}

// SetTotalDeploymentRunSuccess gets a reference to the given int32 and assigns it to the TotalDeploymentRunSuccess field.
func (o *DeploymentAssetMetric) SetTotalDeploymentRunSuccess(v int32) {
	o.TotalDeploymentRunSuccess = &v
}

// GetTotalDeploymentRunError returns the TotalDeploymentRunError field value if set, zero value otherwise.
func (o *DeploymentAssetMetric) GetTotalDeploymentRunError() int32 {
	if o == nil || o.TotalDeploymentRunError == nil {
		var ret int32
		return ret
	}
	return *o.TotalDeploymentRunError
}

// GetTotalDeploymentRunErrorOk returns a tuple with the TotalDeploymentRunError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAssetMetric) GetTotalDeploymentRunErrorOk() (*int32, bool) {
	if o == nil || o.TotalDeploymentRunError == nil {
		return nil, false
	}
	return o.TotalDeploymentRunError, true
}

// HasTotalDeploymentRunError returns a boolean if a field has been set.
func (o *DeploymentAssetMetric) HasTotalDeploymentRunError() bool {
	if o != nil && o.TotalDeploymentRunError != nil {
		return true
	}

	return false
}

// SetTotalDeploymentRunError gets a reference to the given int32 and assigns it to the TotalDeploymentRunError field.
func (o *DeploymentAssetMetric) SetTotalDeploymentRunError(v int32) {
	o.TotalDeploymentRunError = &v
}

// GetTotalDeploymentRunCancel returns the TotalDeploymentRunCancel field value if set, zero value otherwise.
func (o *DeploymentAssetMetric) GetTotalDeploymentRunCancel() int32 {
	if o == nil || o.TotalDeploymentRunCancel == nil {
		var ret int32
		return ret
	}
	return *o.TotalDeploymentRunCancel
}

// GetTotalDeploymentRunCancelOk returns a tuple with the TotalDeploymentRunCancel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAssetMetric) GetTotalDeploymentRunCancelOk() (*int32, bool) {
	if o == nil || o.TotalDeploymentRunCancel == nil {
		return nil, false
	}
	return o.TotalDeploymentRunCancel, true
}

// HasTotalDeploymentRunCancel returns a boolean if a field has been set.
func (o *DeploymentAssetMetric) HasTotalDeploymentRunCancel() bool {
	if o != nil && o.TotalDeploymentRunCancel != nil {
		return true
	}

	return false
}

// SetTotalDeploymentRunCancel gets a reference to the given int32 and assigns it to the TotalDeploymentRunCancel field.
func (o *DeploymentAssetMetric) SetTotalDeploymentRunCancel(v int32) {
	o.TotalDeploymentRunCancel = &v
}

// GetTotalDeploymentRunUnknown returns the TotalDeploymentRunUnknown field value if set, zero value otherwise.
func (o *DeploymentAssetMetric) GetTotalDeploymentRunUnknown() int32 {
	if o == nil || o.TotalDeploymentRunUnknown == nil {
		var ret int32
		return ret
	}
	return *o.TotalDeploymentRunUnknown
}

// GetTotalDeploymentRunUnknownOk returns a tuple with the TotalDeploymentRunUnknown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAssetMetric) GetTotalDeploymentRunUnknownOk() (*int32, bool) {
	if o == nil || o.TotalDeploymentRunUnknown == nil {
		return nil, false
	}
	return o.TotalDeploymentRunUnknown, true
}

// HasTotalDeploymentRunUnknown returns a boolean if a field has been set.
func (o *DeploymentAssetMetric) HasTotalDeploymentRunUnknown() bool {
	if o != nil && o.TotalDeploymentRunUnknown != nil {
		return true
	}

	return false
}

// SetTotalDeploymentRunUnknown gets a reference to the given int32 and assigns it to the TotalDeploymentRunUnknown field.
func (o *DeploymentAssetMetric) SetTotalDeploymentRunUnknown(v int32) {
	o.TotalDeploymentRunUnknown = &v
}

// GetTotalVirtualMachines returns the TotalVirtualMachines field value if set, zero value otherwise.
func (o *DeploymentAssetMetric) GetTotalVirtualMachines() int32 {
	if o == nil || o.TotalVirtualMachines == nil {
		var ret int32
		return ret
	}
	return *o.TotalVirtualMachines
}

// GetTotalVirtualMachinesOk returns a tuple with the TotalVirtualMachines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAssetMetric) GetTotalVirtualMachinesOk() (*int32, bool) {
	if o == nil || o.TotalVirtualMachines == nil {
		return nil, false
	}
	return o.TotalVirtualMachines, true
}

// HasTotalVirtualMachines returns a boolean if a field has been set.
func (o *DeploymentAssetMetric) HasTotalVirtualMachines() bool {
	if o != nil && o.TotalVirtualMachines != nil {
		return true
	}

	return false
}

// SetTotalVirtualMachines gets a reference to the given int32 and assigns it to the TotalVirtualMachines field.
func (o *DeploymentAssetMetric) SetTotalVirtualMachines(v int32) {
	o.TotalVirtualMachines = &v
}

func (o DeploymentAssetMetric) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DeploymentId != nil {
		toSerialize["deploymentId"] = o.DeploymentId
	}
	if o.TotalDeploymentRunDuration != nil {
		toSerialize["totalDeploymentRunDuration"] = o.TotalDeploymentRunDuration
	}
	if o.AverageDeploymentRunDuration != nil {
		toSerialize["averageDeploymentRunDuration"] = o.AverageDeploymentRunDuration
	}
	if o.MedianDeploymentRunDuration != nil {
		toSerialize["medianDeploymentRunDuration"] = o.MedianDeploymentRunDuration
	}
	if o.LongestDeploymentRunDuration != nil {
		toSerialize["longestDeploymentRunDuration"] = o.LongestDeploymentRunDuration
	}
	if o.ShortestDeploymentRunDuration != nil {
		toSerialize["shortestDeploymentRunDuration"] = o.ShortestDeploymentRunDuration
	}
	if o.TotalDeploymentRuns != nil {
		toSerialize["totalDeploymentRuns"] = o.TotalDeploymentRuns
	}
	if o.TotalDeploymentRunSuccess != nil {
		toSerialize["totalDeploymentRunSuccess"] = o.TotalDeploymentRunSuccess
	}
	if o.TotalDeploymentRunError != nil {
		toSerialize["totalDeploymentRunError"] = o.TotalDeploymentRunError
	}
	if o.TotalDeploymentRunCancel != nil {
		toSerialize["totalDeploymentRunCancel"] = o.TotalDeploymentRunCancel
	}
	if o.TotalDeploymentRunUnknown != nil {
		toSerialize["totalDeploymentRunUnknown"] = o.TotalDeploymentRunUnknown
	}
	if o.TotalVirtualMachines != nil {
		toSerialize["totalVirtualMachines"] = o.TotalVirtualMachines
	}
	return json.Marshal(toSerialize)
}

type NullableDeploymentAssetMetric struct {
	value *DeploymentAssetMetric
	isSet bool
}

func (v NullableDeploymentAssetMetric) Get() *DeploymentAssetMetric {
	return v.value
}

func (v *NullableDeploymentAssetMetric) Set(val *DeploymentAssetMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentAssetMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentAssetMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentAssetMetric(val *DeploymentAssetMetric) *NullableDeploymentAssetMetric {
	return &NullableDeploymentAssetMetric{value: val, isSet: true}
}

func (v NullableDeploymentAssetMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentAssetMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
