/*
CONS3RT API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@cons3rt.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InputConfiguration struct for InputConfiguration
type InputConfiguration struct {
	Script string `json:"script"`
}

// NewInputConfiguration instantiates a new InputConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputConfiguration(script string) *InputConfiguration {
	this := InputConfiguration{}
	this.Script = script
	return &this
}

// NewInputConfigurationWithDefaults instantiates a new InputConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputConfigurationWithDefaults() *InputConfiguration {
	this := InputConfiguration{}
	return &this
}

// GetScript returns the Script field value
func (o *InputConfiguration) GetScript() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Script
}

// GetScriptOk returns a tuple with the Script field value
// and a boolean to check if the value has been set.
func (o *InputConfiguration) GetScriptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Script, true
}

// SetScript sets field value
func (o *InputConfiguration) SetScript(v string) {
	o.Script = v
}

func (o InputConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["script"] = o.Script
	}
	return json.Marshal(toSerialize)
}

type NullableInputConfiguration struct {
	value *InputConfiguration
	isSet bool
}

func (v NullableInputConfiguration) Get() *InputConfiguration {
	return v.value
}

func (v *NullableInputConfiguration) Set(val *InputConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableInputConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableInputConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputConfiguration(val *InputConfiguration) *NullableInputConfiguration {
	return &NullableInputConfiguration{value: val, isSet: true}
}

func (v NullableInputConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
